# Generated by Django 6.0.3 on 2026-03-27 05:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_xp', models.IntegerField(db_index=True, default=0)),
                ('educator_xp', models.IntegerField(default=0)),
                ('builder_xp', models.IntegerField(default=0)),
                ('creator_xp', models.IntegerField(default=0)),
                ('scout_xp', models.IntegerField(default=0)),
                ('diplomat_xp', models.IntegerField(default=0)),
                ('skill_tree_state', models.JSONField(default=dict, help_text='Map of node_id → ISO timestamp of when unlocked.')),
                ('rank', models.IntegerField(blank=True, db_index=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
