# Generated by Django 5.2.6 on 2026-03-26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraphNode",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("node_key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("node_type", models.CharField(choices=[("account", "Account"), ("content", "Content"), ("entity", "Entity"), ("signal", "Signal")], db_index=True, max_length=24)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("source_platform", models.CharField(choices=[("twitter", "Twitter/X"), ("discord", "Discord"), ("telegram", "Telegram"), ("github", "GitHub"), ("manual", "Manual")], db_index=True, default="manual", max_length=16)),
                ("payload", models.JSONField(default=dict)),
                ("ingestion_batch_id", models.CharField(blank=True, default="", max_length=64)),
                ("raw_ref", models.CharField(blank=True, default="", max_length=255)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "db_table": "spore_graph_nodes",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["node_type", "source_platform"], name="spore_graph__node_ty_4ed4f2_idx"), models.Index(fields=["is_deleted", "-updated_at"], name="spore_graph__is_dele_8a24a5_idx")],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_platform", models.CharField(choices=[("twitter", "Twitter/X"), ("discord", "Discord"), ("telegram", "Telegram"), ("github", "GitHub"), ("manual", "Manual")], db_index=True, max_length=16)),
                ("source_event_id", models.CharField(db_index=True, max_length=255)),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("actor_external_id", models.CharField(db_index=True, max_length=255)),
                ("target_external_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("content_text", models.TextField(blank=True, default="")),
                ("content_url", models.URLField(blank=True, default="")),
                ("content_hash", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("occurred_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "spore_observations",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["actor_external_id", "target_external_id"], name="spore_obser_actor_e_4e9e95_idx"), models.Index(fields=["source_platform", "-occurred_at"], name="spore_obser_source__ba9abf_idx")],
                "constraints": [models.UniqueConstraint(fields=("source_platform", "source_event_id", "event_type"), name="uniq_spore_observation_source_event_type")],
            },
        ),
        migrations.CreateModel(
            name="ScoreRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contribution_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("source_platform", models.CharField(choices=[("twitter", "Twitter/X"), ("discord", "Discord"), ("telegram", "Telegram"), ("github", "GitHub"), ("manual", "Manual")], default="manual", max_length=16)),
                ("score_version", models.CharField(default="spore-v1", max_length=32)),
                ("context", models.JSONField(default=dict)),
                ("variable_scores", models.JSONField(default=dict)),
                ("explainability", models.JSONField(default=dict)),
                ("confidence", models.FloatField(default=0.0)),
                ("final_score", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "spore_score_runs",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["contribution_id", "-created_at"], name="spore_score_contribu_b3cf8c_idx"), models.Index(fields=["source_platform", "score_version"], name="spore_score_source__d5af39_idx")],
            },
        ),
        migrations.CreateModel(
            name="GraphEdge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("edge_type", models.CharField(choices=[("authored", "Authored"), ("mentions", "Mentions"), ("reply_to", "Reply To"), ("quotes", "Quotes"), ("semantic", "Semantic"), ("interacts", "Interacts"), ("follows", "Follows"), ("co_occurs", "Co-occurs")], db_index=True, max_length=32)),
                ("source_platform", models.CharField(choices=[("twitter", "Twitter/X"), ("discord", "Discord"), ("telegram", "Telegram"), ("github", "GitHub"), ("manual", "Manual")], db_index=True, default="manual", max_length=16)),
                ("weight", models.FloatField(default=1.0)),
                ("metadata", models.JSONField(default=dict)),
                ("last_seen_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("from_node", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="out_edges", to="spore.graphnode")),
                ("to_node", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="in_edges", to="spore.graphnode")),
            ],
            options={
                "db_table": "spore_graph_edges",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["edge_type", "source_platform"], name="spore_graph__edge_ty_4f66aa_idx"), models.Index(fields=["from_node", "edge_type"], name="spore_graph__from_no_7f5223_idx"), models.Index(fields=["to_node", "edge_type"], name="spore_graph__to_node_0c36a2_idx")],
                "constraints": [models.UniqueConstraint(fields=("from_node", "to_node", "edge_type", "source_platform"), name="uniq_spore_graph_edge")],
            },
        ),
    ]

