# Generated by Django 6.0.3 on 2026-03-26 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphedge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='graphnode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scorerun',
            options={},
        ),
        migrations.RenameIndex(
            model_name='graphedge',
            new_name='spore_graph_edge_ty_a92bf3_idx',
            old_name='spore_graph__edge_ty_4f66aa_idx',
        ),
        migrations.RenameIndex(
            model_name='graphedge',
            new_name='spore_graph_from_no_a9748e_idx',
            old_name='spore_graph__from_no_7f5223_idx',
        ),
        migrations.RenameIndex(
            model_name='graphedge',
            new_name='spore_graph_to_node_31df70_idx',
            old_name='spore_graph__to_node_0c36a2_idx',
        ),
        migrations.RenameIndex(
            model_name='graphnode',
            new_name='spore_graph_node_ty_146d25_idx',
            old_name='spore_graph__node_ty_4ed4f2_idx',
        ),
        migrations.RenameIndex(
            model_name='graphnode',
            new_name='spore_graph_is_dele_4dacc8_idx',
            old_name='spore_graph__is_dele_8a24a5_idx',
        ),
        migrations.RenameIndex(
            model_name='observation',
            new_name='spore_obser_actor_e_1e6e01_idx',
            old_name='spore_obser_actor_e_4e9e95_idx',
        ),
        migrations.RenameIndex(
            model_name='observation',
            new_name='spore_obser_source__2e14e0_idx',
            old_name='spore_obser_source__ba9abf_idx',
        ),
        migrations.RenameIndex(
            model_name='scorerun',
            new_name='spore_score_contrib_19513e_idx',
            old_name='spore_score_contribu_b3cf8c_idx',
        ),
        migrations.RenameIndex(
            model_name='scorerun',
            new_name='spore_score_source__d02e1c_idx',
            old_name='spore_score_source__d5af39_idx',
        ),
    ]
