# Generated by Django 6.0.3 on 2026-03-26 04:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spore', '0002_alter_graphedge_options_alter_graphnode_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphQueryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_text', models.TextField()),
                ('query_hash', models.CharField(db_index=True, max_length=32)),
                ('hops', models.IntegerField(default=2)),
                ('damping', models.FloatField(default=0.65)),
                ('top_k', models.IntegerField(default=10)),
                ('seed_nodes', models.JSONField(default=list)),
                ('result_count', models.IntegerField(default=0)),
                ('results', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spore_graph_query_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spore_graph_query_runs',
                'indexes': [models.Index(fields=['user', '-created_at'], name='spore_graph_user_id_5d39ba_idx'), models.Index(fields=['query_hash', '-created_at'], name='spore_graph_query_h_03df13_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelationshipAnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_a', models.CharField(db_index=True, max_length=255)),
                ('account_b', models.CharField(db_index=True, max_length=255)),
                ('days', models.IntegerField(default=30)),
                ('features', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spore_relationship_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spore_relationship_analysis_runs',
                'indexes': [models.Index(fields=['user', '-created_at'], name='spore_relat_user_id_7e3c29_idx'), models.Index(fields=['account_a', 'account_b', '-created_at'], name='spore_relat_account_cf507d_idx')],
            },
        ),
    ]
