# Generated by Django 6.0.3 on 2026-03-26 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spore', '0003_graphqueryrun_relationshipanalysisrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spore_score_runs', to=settings.AUTH_USER_MODEL),
        ),
    ]
