# Generated by Django 6.0.3 on 2026-03-26 04:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spore', '0004_scorerun_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.CharField(default='starter', max_length=32)),
                ('quota_daily_query', models.IntegerField(default=1000)),
                ('quota_daily_ingest', models.IntegerField(default=500)),
                ('quota_daily_relationship', models.IntegerField(default=1000)),
                ('quota_daily_brief_generate', models.IntegerField(default=200)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'spore_tenants',
                'indexes': [models.Index(fields=['slug', 'is_active'], name='spore_tenan_slug_77ee23_idx')],
            },
        ),
        migrations.CreateModel(
            name='SporeApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('prefix', models.CharField(db_index=True, max_length=16)),
                ('key_hash', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spore_api_keys', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='spore.tenant')),
            ],
            options={
                'db_table': 'spore_api_keys',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=96)),
                ('target_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spore_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='spore.sporeapikey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='spore.tenant')),
            ],
            options={
                'db_table': 'spore_audit_logs',
            },
        ),
        migrations.AddField(
            model_name='graphqueryrun',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_runs', to='spore.tenant'),
        ),
        migrations.AddField(
            model_name='relationshipanalysisrun',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_runs', to='spore.tenant'),
        ),
        migrations.AddField(
            model_name='scorerun',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_runs', to='spore.tenant'),
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='spore.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spore_tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spore_tenant_memberships',
            },
        ),
        migrations.CreateModel(
            name='UsageDailyCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(max_length=64)),
                ('day', models.DateField(db_index=True)),
                ('count', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_counters', to='spore.tenant')),
            ],
            options={
                'db_table': 'spore_usage_daily_counters',
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(db_index=True, max_length=64)),
                ('units', models.IntegerField(default=1)),
                ('status_code', models.IntegerField(db_index=True, default=200)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='spore.sporeapikey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='spore.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spore_usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spore_usage_events',
            },
        ),
        migrations.AddIndex(
            model_name='sporeapikey',
            index=models.Index(fields=['tenant', 'is_active'], name='spore_api_k_tenant__f9a128_idx'),
        ),
        migrations.AddIndex(
            model_name='sporeapikey',
            index=models.Index(fields=['prefix', 'is_active'], name='spore_api_k_prefix_2feb10_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'action', '-created_at'], name='spore_audit_tenant__9d179e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id', '-created_at'], name='spore_audit_target__a8b4e0_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'role', 'is_active'], name='spore_tenan_tenant__65189d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user', 'is_active'], name='spore_tenan_user_id_1791b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='uniq_spore_tenant_user_membership'),
        ),
        migrations.AddIndex(
            model_name='usagedailycounter',
            index=models.Index(fields=['tenant', 'day'], name='spore_usage_tenant__b59b19_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagedailycounter',
            constraint=models.UniqueConstraint(fields=('tenant', 'metric', 'day'), name='uniq_spore_usage_daily_counter'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['tenant', 'metric', '-created_at'], name='spore_usage_tenant__41ba5c_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['user', '-created_at'], name='spore_usage_user_id_c6044b_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['api_key', '-created_at'], name='spore_usage_api_key_1fa03e_idx'),
        ),
    ]
