# Generated by hand to create approvals models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirdropPayoutApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("batch_id", models.CharField(max_length=128, blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        related_name="approvals_created",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.user",
                        blank=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        related_name="approvals_approved",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.user",
                        blank=True,
                    ),
                ),
            ],
            options={
                "db_table": "rewards_airdrop_payout_approval",
            },
        ),
        migrations.CreateModel(
            name="ApprovalAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("created", "created"), ("approved", "approved"), ("updated", "updated")], max_length=32)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("approval", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audits", to="approvals.airdroppayoutapproval")),
                ("actor", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="accounts.user", blank=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
