# Generated by Django 6.0.3 on 2026-03-27 05:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], db_index=True, max_length=16)),
                ('chain', models.CharField(choices=[('avalanche', 'Avalanche'), ('base', 'Base'), ('solana', 'Solana')], default='avalanche', max_length=16)),
                ('contract_address', models.CharField(blank=True, default='', max_length=42)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'badges',
            },
        ),
        migrations.CreateModel(
            name='LootChest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], db_index=True, max_length=16)),
                ('loot_type', models.CharField(blank=True, choices=[('badge', 'Badge NFT'), ('innovator_token', 'InnovatorToken'), ('multiplier', 'XP Multiplier')], max_length=32, null=True)),
                ('loot_name', models.CharField(blank=True, default='', max_length=255)),
                ('loot_description', models.TextField(blank=True, default='')),
                ('loot_amount', models.IntegerField(blank=True, null=True)),
                ('opened', models.BooleanField(db_index=True, default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', help_text="e.g. 'quest_completion', 'milestone', 'daily'", max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loot_chests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loot_chests',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nft_token_id', models.CharField(blank=True, default='', max_length=255)),
                ('minted', models.BooleanField(default=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='rewards.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_badges',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
