# Generated by Django 6.0.3 on 2026-03-27 05:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('educator', 'Educator'), ('builder', 'Builder'), ('creator', 'Creator'), ('scout', 'Scout'), ('diplomat', 'Diplomat')], db_index=True, max_length=16)),
                ('period', models.CharField(choices=[('all_time', 'All Time'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=16)),
                ('rank', models.IntegerField(db_index=True)),
                ('xp', models.IntegerField(default=0)),
                ('contribution_count', models.IntegerField(default=0)),
                ('snapshot_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaderboard_entries',
                'ordering': ['rank'],
                'unique_together': {('user', 'scope', 'period')},
            },
        ),
    ]
