# Generated by Django 6.0.3 on 2026-05-22 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_twitterconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterconnection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='twitterconnection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twitterconnection',
            name='use_selenium_fallback',
            field=models.BooleanField(default=False, help_text='When true and API poll fails, attempt Selenium scrape (dev only).'),
        ),
    ]
