# Generated by Django 6.0.3 on 2026-05-22 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_twitterconnection_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('twitter', 'Twitter / X'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('github', 'GitHub')], db_index=True, max_length=20)),
                ('external_id', models.CharField(help_text='Platform-specific user ID', max_length=128)),
                ('username', models.CharField(blank=True, default='', max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('access_token', models.TextField(blank=True, default='')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['platform'], name='accounts_us_platfor_f8584c_idx'), models.Index(fields=['user', 'platform'], name='accounts_us_user_id_cb4542_idx')],
                'unique_together': {('user', 'platform', 'external_id')},
            },
        ),
    ]
