# Generated by Django 6.0.3 on 2026-03-27 05:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('teaching_value_weight', models.FloatField(default=0.333)),
                ('originality_weight', models.FloatField(default=0.333)),
                ('community_impact_weight', models.FloatField(default=0.334)),
                ('custom_instructions', models.TextField(blank=True, help_text='Additional instructions appended to the base AI Judge prompt.')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'scoring_rubrics',
            },
        ),
        migrations.CreateModel(
            name='JudgeCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('content_text', models.TextField()),
                ('teaching_value', models.IntegerField()),
                ('originality', models.IntegerField()),
                ('community_impact', models.IntegerField()),
                ('composite_score', models.IntegerField()),
                ('farming_flag', models.CharField(choices=[('genuine', 'Genuine'), ('farming', 'Farming'), ('ambiguous', 'Ambiguous')], max_length=16)),
                ('farming_explanation', models.TextField()),
                ('dimension_explanations', models.JSONField(default=dict)),
                ('model_used', models.CharField(default='claude-sonnet-4-20250514', max_length=64)),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.scoringrubric')),
            ],
            options={
                'db_table': 'judge_cache',
            },
        ),
    ]
