# Generated by Django 6.0.3 on 2026-03-23 04:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('github', 'GitHub')], db_index=True, max_length=16)),
                ('content_text', models.TextField()),
                ('content_url', models.URLField(blank=True, default='')),
                ('platform_content_id', models.CharField(blank=True, default='', help_text='Native ID on the platform (tweet ID, GitHub PR number, etc.)', max_length=255)),
                ('teaching_value', models.IntegerField(blank=True, null=True)),
                ('originality', models.IntegerField(blank=True, null=True)),
                ('community_impact', models.IntegerField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, db_index=True, null=True)),
                ('farming_flag', models.CharField(blank=True, choices=[('genuine', 'Genuine'), ('farming', 'Farming'), ('ambiguous', 'Ambiguous')], db_index=True, max_length=16, null=True)),
                ('farming_explanation', models.TextField(blank=True, default='')),
                ('dimension_explanations', models.JSONField(default=dict)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contributions',
                'indexes': [models.Index(fields=['user', '-created_at'], name='contributio_user_id_45f7a2_idx'), models.Index(fields=['platform', '-created_at'], name='contributio_platfor_5c0eef_idx')],
                'unique_together': {('platform', 'platform_content_id')},
            },
        ),
        migrations.CreateModel(
            name='CrawlSourceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('discord', 'Discord'), ('telegram', 'Telegram')], db_index=True, max_length=16)),
                ('source_key', models.CharField(help_text='Twitter username, Discord channel ID, or Telegram chat ID', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('cursor', models.CharField(blank=True, default='', help_text='Incremental cursor (latest seen message ID) for this source', max_length=255)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contribution_crawl_source_configs',
                'indexes': [models.Index(fields=['platform', 'is_active'], name='contributio_platfor_94b098_idx'), models.Index(fields=['user', 'is_active'], name='contributio_user_id_a80cbb_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'platform', 'source_key'), name='uniq_crawl_source_per_user')],
            },
        ),
    ]
