# Generated by Django 6.0.3 on 2026-03-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='platform',
            field=models.CharField(choices=[('twitter', 'Twitter/X'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('reddit', 'Reddit'), ('github', 'GitHub')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='crawlsourceconfig',
            name='platform',
            field=models.CharField(choices=[('twitter', 'Twitter/X'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('reddit', 'Reddit')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='crawlsourceconfig',
            name='source_key',
            field=models.CharField(help_text='Twitter username, Discord channel ID, Telegram chat ID, or subreddit name', max_length=255),
        ),
    ]
