# Generated by Django 6.0.3 on 2026-03-27 05:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_name', models.CharField(max_length=255)),
                ('project_logo_url', models.URLField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], db_index=True, max_length=1)),
                ('reward_pool', models.DecimalField(decimal_places=6, max_digits=20)),
                ('reward_token', models.CharField(blank=True, default='', max_length=42)),
                ('chain', models.CharField(choices=[('avalanche', 'Avalanche'), ('base', 'Base'), ('solana', 'Solana')], default='avalanche', max_length=16)),
                ('scoring_rubric', models.JSONField(default=dict, help_text='{"rubric_id": "<uuid>"} or inline weights.')),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('party_size', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], db_index=True, default='upcoming', max_length=16)),
            ],
            options={
                'db_table': 'quests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=16)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='quests.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quest_acceptances',
                'unique_together': {('quest', 'user')},
            },
        ),
    ]
