# Generated by Django 6.0.3 on 2026-05-22 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0002_alter_contribution_platform_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(choices=[('contribution', 'Contribution score'), ('account', 'Account farming flag')], default='contribution', max_length=16)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('upheld', 'Upheld'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('snapshot_farming_flag', models.CharField(blank=True, default='', max_length=16)),
                ('snapshot_composite_score', models.IntegerField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='contributions.contribution')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_score_appeals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_appeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integrity_score_appeals',
                'indexes': [models.Index(fields=['status', '-created_at'], name='integrity_s_status_c6e96f_idx'), models.Index(fields=['user', '-created_at'], name='integrity_s_user_id_833465_idx')],
            },
        ),
    ]
