# Generated by Django 6.0.3 on 2026-03-26 10:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spore', '0005_tenant_sporeapikey_auditlog_graphqueryrun_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_subscription_item_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_latest_event_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('plan', models.CharField(choices=[('starter', 'Starter — $99/mo'), ('growth', 'Growth — $499/mo'), ('enterprise', 'Enterprise — Custom')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('trialing', 'Trialing'), ('incomplete', 'Incomplete')], default='trialing', max_length=16)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='spore.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
                'indexes': [models.Index(fields=['plan', 'status'], name='subscriptio_plan_6e710f_idx')],
            },
        ),
    ]
